[package]
name = "server"
version = "0.1.0"
authors = ["davidpodhola <david.podhola@hsharp.software>"]

[dependencies]
nickel = "*"
bson = "*"
mongodb  = "*"
clippy = {version = "*", optional = true}
iis = "*"
nickel-jwt-session = { version = "*",path = "../lib/nickel-jwt-session" }

[features]
default = []

[dependencies.hyper]
version = "*"
default-features = false

[dependencies.cookie]
version = "*"
default-features = false
