[package]
name = "server"
version = "0.1.0"
authors = ["davidpodhola <david.podhola@hsharp.software>"]

[dependencies]
nickel = "*"
bson = "*"
mongodb  = "*"
clippy = {version = "*", optional = true}
iis = "*"
hyper = "*"

[features]
default = []
